license = "BSD3"
version_control = "darcs"
version = "0.1.0"

[author]
name = "Vanessa McHale"
email = "vamchale@gmail.com"
github_username = "vmchale"

[[custom_keys]]
website = "https://vmchale.com"
